---
title: "Travel Heatmap Gallery"
author: "Rachael Caelie (Rocky) Aikens and Elizabeth Chin"
date: "5/24/2019"
output: html_document
---

```{r setup, warning=FALSE, message = FALSE, include = FALSE}
knitr::opts_chunk$set(cache=TRUE, warning = FALSE, message = FALSE, echo = FALSE, fig.align = "center", fig.height = 4)
library(ggplot2)
library(dplyr)
library(gridExtra)
library(ggpubr)
theme_set(theme_light())
source("build_heatmaps.R")
source("build_interactive.R")
```

# Set Up

First we need to get the census tract locations and demographics.  Census tracts have a unique GEOID, which we use to join data frames.

```{r include=FALSE}
census_api_key("6020dd87f4d614074553da9b317878cb026a7c88")

CA_census <- get_acs(geography = "tract", 
                     variables = "B01003_001", 
                     state = "CA",
                     geometry = TRUE) %>%
  mutate(GEOID = as.numeric(GEOID))
```

One thing to note is that Rmarkdown and leaflet don't seem to play well together.

# Geodesic Distance

The plots below show geometric distance to the nearest general acute care facility.

```{r}
hosp_df <- read_csv("../data/hospDataClean.csv")
distance_df <- read_csv("../data/GeoDistances.csv")
make_map(CA_census, distance_df, hosp_df)
```

# Travel time

```{r}
source("build_interactive.R")
hosp_df <- read_csv("../data/safetynetDataClean.csv")
travel_df <- read_csv("../data/map_times_safetynet_noncongested.csv")

build_heatmap(CA_census, travel_df, hosp_df, "Hospital travel time in minutes", "travel_change_hospital_noncongested.csv")
```

